### ISSUE TITLE
新创建项目启动失败

### ISSUE THREAD

**Issue by zhutongtian** [steedos/object-server#192]
PS E:\my-app> yarn start
yarn run v1.21.0
$ node server.js
*******************************************************************
*
*  Initialize Steedos Server ...
*
*  VERSION: 1.12.1
*  PORT: 5000
*  ROOT_URL: http://127.0.0.1:5000
*  MONGO_URL: mongodb://127.0.0.1/steedos
*  PROJECT_DIR: E:\my-app
*  STORAGE_DIR: E:\my-app\storage
*
*******************************************************************
(node:477864) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:477864) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
WARNING: npm peer requirements (for steedos:cfs-data-man) not installed:
 - mime@1.6.0 installed, mime@^2.0.2 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

(node:477864) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
(node:477864) UnhandledPromiseRejectionWarning: Error: Plugin not found in project, please execute: yarn add @steedos/steedos-plugin-workflow
    at _.each (E:\my-app\node_modules\@steedos\core\src\init\plugins.ts:31:31)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (E:\my-app\node_modules\underscore\underscore.js:79:11)
    at Function.init (E:\my-app\node_modules\@steedos\core\src\init\plugins.ts:20:15)
    at Object.init (E:\my-app\node_modules\@steedos\core\src\init\index.ts:12:13)
    at E:\my-app\server.js:8:21
    at Function.run (E:\my-app\node_modules\@steedos\meteor-bundle-runner\src\profile.js:510:12)
    at E:\my-app\server.js:6:24
(node:477864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:477864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js 
process with a non-zero exit code.
TypeError: Cannot read property 'fields' of undefined
    at new Creator.Object (meteor://�💻app/packages/steedos_objects/lib/object.coffee:63:29)
    at meteor://�💻app/packages/steedos_objects/lib/object.coffee:232:4
    at Function.each (packages\underscore.js:147:22)
    at meteor://�💻app/packages/steedos_objects/lib/object.coffee:231:5
    at Function.time (E:\my-app\node_modules\@steedos\meteor-bundle-runner\src\profile.js:309:28)
    at Object.callStartupHooks (E:\my-app\node_modules\@steedos\meteor-bundle-runner\src\boot.js:429:13)
    at E:\my-app\server.js:9:20
    at Function.run (E:\my-app\node_modules\@steedos\meteor-bundle-runner\src\profile.js:510:12)
    at E:\my-app\server.js:6:24

**Comment by hotlong** [comment]
yarn add @steedos/steedos-plugin-workflow
