### ISSUE TITLE
连接mysql数据库报错

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#73]
driver: "mysql",
url: "mysql://mailcow:xxxxxx@127.0.0.1:13306/mailcow",

{ Error: Option "database" is not set in your connection options, please define "database" option in your connection options or ormconfig.json
    at new NoConnectionOptionError (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/error/NoConnectionOptionError.ts:7:9)
    at EntityMetadataValidator.validate (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/metadata-builder/EntityMetadataValidator.ts:101:23)
    at /Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/metadata-builder/EntityMetadataValidator.ts:44:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/metadata-builder/EntityMetadataValidator.ts:44:25)
    at Connection.buildMetadatas (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/connection/Connection.ts:509:33)
    at Connection.<anonymous> (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/src/connection/Connection.ts:190:18)
    at step (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/steedos/Documents/GitHub/steedos-plugin-mailcow/node_modules/tslib/tslib.js:104:62)
    at /Users/steedos/Documents/GitHub/steedos-plugin-mailcow/node_modules/meteor-promise/fiber_pool.js:43:39
  message:
   'Option "database" is not set in your connection options, please define "database" option in your connection options or ormconfig.json' }

**Comment by hotlong** [comment]
完整的代码在这里： https://github.com/steedos/steedos-plugin-mailcow
