### ISSUE TITLE
在一个空库上试用 contracts-app，注册账户之后显示空屏

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#84]
(node:3896) UnhandledPromiseRejectionWarning: Error: not find datasource default
    at SteedosSchema.getObject (C:\Users\steedos\Documents\Github\steedos-contracts-app\node_modules\@steedos\auth\node_modules\@steedos\objectql\src\types\schema.ts:70:19)
    at getUser (C:\Users\steedos\Documents\Github\steedos-contracts-app\node_modules\@steedos\auth\src\session.ts:68:40)
    at Object.getSession (C:\Users\steedos\Documents\Github\steedos-contracts-app\node_modules\@steedos\auth\src\session.ts:134:22)
    at getSession (meteor://💻app/packages/steedos_base/server/routes/bootstrap.coffee:31:16)
    at packages\meteor.js:376:21
    at meteor://💻app/packages/steedos_base/server/routes/bootstrap.coffee:30:16
    at handler (meteor://💻app/packages/simple:json-routes/json-routes.js:88:9)

**Comment by hotlong** [comment]
好像是加载配置文件失败

**Comment by hotlong** [comment]
object-server/apps/contracts 可以正常运行。
